# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'
source 'https://github.com/dondong/DDSwiftRuntime.git'

target 'DDSwiftHookDemo' do
    pod 'DDSwiftRuntime'
end
